#!/usr/bin/env python
# -*- coding: utf-8 -*-
# parsev, part for parse_video : a fork from parseVideo. 
# parsev: parse_video start script, should be run in python3. 
# version 0.1.1.0 test201505061514
# author sceext <sceext@foxmail.com> 2009EisF2015, 2015.05. 
# copyright 2015 sceext
#
# This is FREE SOFTWARE, released under GNU GPLv3+ 
# please see README.md and LICENSE for more information. 
#
#    parse_video : a fork from parseVideo. 
#    Copyright (C) 2015 sceext <sceext@foxmail.com> 
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# import

from lib import entry
from lib import error
from bin import parse_video

# main function
def main():
    # set import
    parse_video.set_import(entry, error)
    # just start it
    return parse_video.main()

# start from main
if __name__ == '__main__':
    ret = main()
    if ret == None:
        ret = 0
    exit(ret)

# end parsev


