#!/usr/bin/env python3.5
# -*- coding: utf-8 -*-
# parsev, parse_video/

import os, sys

def start():
    sys.path.insert(0, os.path.dirname(__file__))
    from bin import parse_video
    parse_video.main(sys.argv[1:])

if __name__ == '__main__':
    start()
# end parsev


