# gen_list_file.py, parse_video/o/plist/lib/

from . import b, conf

def make_list_text(plinfo):
    # gen lines
    out = []
    out += _gen_start_lines(plinfo)
    out += _gen_list_lines(plinfo)
    out += _gen_end_lines(plinfo)
    # join lines
    text = ('\n').join(out) + '\n\n'
    # make list file_name
    file_name = _gen_file_name(plinfo)
    return text, file_name

def _gen_title(plinfo):
    info = plinfo['info']
    title = ('_').join([info['title'], info['site_name']])
    return title

def _gen_file_name(plinfo):
    info = plinfo['info']
    title = _gen_title(plinfo)
    # NOTE the list is used by pvdl
    out = ('.').join(['pl', title, str(plinfo['count']), 'pvdl', 'list'])
    return b.replace_filename_bad_char(out)

def _gen_start_lines(plinfo):
    out = []
    # first NOTE line
    one = 'NOTE: this file is auto-generated by plist (' + conf.plist_version + '). '
    one += 'And this file is used by pvdl. '
    out += [one]
    # second INFO line
    info = plinfo
    title = _gen_title(plinfo)
    one = 'count ' + str(plinfo['count']) + ' [' + title + '] '
    one += ' URL: ' + info['url']
    # TODO add more info here
    out += [one]
    # add '# ' before each line
    for i in range(len(out)):
        out[i] = '# ' + out[i]
    return out

def _gen_list_lines(plinfo):
    out = []
    # gen each item
    for i in range(len(plinfo['list'])):
        raw = plinfo['list'][i]
        item = ['']	# add a blank line before each list item
        item.append(raw['url'])	# add URL first
        # second line, the description
        title = _gen_sub_title(raw, i, plinfo)
        # TODO support time_s
        time = raw.get('time', '')
        one = '(' + str(i) + '/' + str(plinfo['count']) + ') ' + title + ' ' + time + ' '
        item += ['# ' + one]
        out += item
    return out

def _gen_sub_title(item, i, plinfo):
    info = plinfo['info']
    # gen title_no
    title_no = item.get('title_no', i)
    title_no = str(title_no).zfill(4)
    
    # get other info
    title = item.get('title', '')
    title_sub = item.get('title_sub', '')
    
    out = ('_').join([title_no, info['title'], title, title_sub])
    return out

def _gen_end_lines(plinfo):
    # add last_update
    one = 'last_update ' + plinfo['last_update']
    out = ['', '# ' + one]	# NOTE add a blank line before last_update
    return out

# end gen_list_file.py


