#!/usr/bin/env python
# -*- coding: utf-8 -*-
# parsev, parse_video/
# LICENSE GNU GPLv3+ sceext 
# version 0.0.1.0 test201509272027

'''
'''

import sys

# try to fix import
try:
    from . import lib
    from .bin import parse_video as pv
except Exception:
    import lib
    from bin import parse_video as pv

def start():
    # set import lib to bin/parse_video
    pv.lib = lib
    pv.main(sys.argv[1:])

if __name__ == '__main__':
    start()

# end parsev


